feat: extraction of boundary types from various docstrings
Safe-DS/Library-Analyzer pull request #111
Opened 2023-04-26 15:52 UTC by nvollroth

Closes #48, closes #36, closes #35, closes #32, closes #31, closes #30, closes #27, closes #8.
 

### Summary of Changes

SpaCy rules were generated to recognize named examples and extract the resulting boundaries. 

### Instructions for Manual Testing (if required)

1. Run `pytest` for `test_extract_boundary_values.py`.
2. Check the results of `pytest`.

2023-04-26 15:54 UTC, lars-reimann commented
## [🦙 MegaLinter](https://megalinter.io/6.22.1) status: ❌ [ERROR](https://github.com/Safe-DS/Library-Analyzer/actions/runs/4810754651)

| Descriptor  |                                 Linter                                 |Files|Fixed|                                 Errors                                 |Elapsed time|
|-------------|------------------------------------------------------------------------|-----|----:|------------------------------------------------------------------------|------------|
|✅ PYTHON    |[black](https://megalinter.io/6.22.1/descriptors/python_black)          |    2|    2|                                                                       0|1.09s       |
|❌ PYTHON    |[mypy](https://megalinter.io/6.22.1/descriptors/python_mypy)            |    2|     |[6](https://github.com/Safe-DS/Library-Analyzer/actions/runs/4810754651)|1.92s       |
|❌ PYTHON    |[ruff](https://megalinter.io/6.22.1/descriptors/python_ruff)            |    2|    2|[9](https://github.com/Safe-DS/Library-Analyzer/actions/runs/4810754651)|0.06s       |
|✅ REPOSITORY|[git_diff](https://megalinter.io/6.22.1/descriptors/repository_git_diff)|yes  |     |no                                                                      |0.03s       |

See detailed report in [MegaLinter reports](https://github.com/Safe-DS/Library-Analyzer/actions/runs/4810754651)
_Set `VALIDATE_ALL_CODEBASE: true` in mega-linter.yml to validate all sources, not only the diff_

_MegaLinter is graciously provided by [![OX Security](https://www.ox.security/wp-content/uploads/2022/06/logo.svg?ref=megalinter_comment)](https://www.ox.security/?ref=megalinter)_
<!-- MegaLinter Status Report -->

<!-- megalinter: github-comment-reporter workflow='MegaLinter' jobid='lint' -->

2023-04-28 09:09 UTC, lars-reimann commented
@nvollroth Add a comment `# noqa: ARG001` to the end of the problematic lines. See the [`ruff` docs](https://beta.ruff.rs/docs/configuration/#error-suppression) for more details.

2023-04-29 16:03 UTC, lars-reimann commented
@nvollroth The linter check passes now.

2023-05-04 09:16 UTC, lars-reimann requested changes

2023-05-04 09:16 UTC, lars-reimann commented on src/library_analyzer/processing/api/_extract_boundary_values.py
> +    def add_boundary(self, match_label: str, type_: str, match_string: Span = None) -> None:
A docstring for this would be great.

2023-05-05 12:43 UTC, nvollroth commented on src/library_analyzer/processing/api/_extract_boundary_values.py
> +    def add_boundary(self, match_label: str, type_: str, match_string: Span = None) -> None:
Added a docstring for the add_boundary function.

2023-05-05 13:06 UTC, nvollroth commented
@lars-reimann 
All changes have been done and the code is now ready for review.

2023-05-05 16:23 UTC, lars-reimann approved these changes

2023-05-05 16:23 UTC, merged