fix: data structure refactor
Safe-DS/Library-Analyzer pull request #223
Opened 2024-02-16 16:48 UTC by lukarade

### Summary of Changes

In this fix, the data structure is reworked to fit the model discussed in the requirements.

Also, the analysis is changed regarding the resolving of references. 
It should now be more efficient and easier to understand since the changes to the data structures below were used.

Added the class `Reference` to represent a node that references a `Symbol`. This class is also used to store the references to the symbols. Therefor the `ReferenceNode` class is obsolete and therefore removed.
Removed the `Reasons` class and added it functionality to the `FunctionScope` class (target, value and call nodes).

This blocks the merge of #211!

2024-02-27 12:39 UTC, lukarade commented
The code coverage percentage for `_module_data.py` and `_get_module_data.py` is higher than calculated. This is due to the test cases for running the analysis on a complete package are disabled (for now).

2024-02-27 16:26 UTC, lars-reimann requested changes
For the files in `processing/api/purity_analysis` I've only done some spot checks. I currently don't have the time to review them completely.

2024-02-27 16:26 UTC, lars-reimann commented on src/library_analyzer/processing/api/purity_analysis/model/_purity.py
> +    def to_result_str(self) -> str:
Is this essentially the `__repr__` (machine readable, unique) or `__str__` (human readable) method? If so, better use that instead.

Also for other classes below.

2024-02-27 16:26 UTC, lars-reimann commented on src/library_analyzer/processing/api/purity_analysis/model/_reference.py
> +    This is used to represent a Reference from a function call to the function definition.
a reference (lower case)

2024-02-27 16:26 UTC, lars-reimann commented on src/library_analyzer/processing/api/purity_analysis/model/_reference.py
> +    After the references of aaa module have been resolved, all necessary information for the purity analysis is available in this class.
of a module (not aaa)

2024-02-27 16:26 UTC, lars-reimann commented on src/library_analyzer/processing/api/purity_analysis/model/_reference.py
> +    unknown_calls: list[astroid.Call | astroid.NodeNG] | None = field(default=None)
Why is this a list, while everything else is a set? Could we also use an empty list/set instead of `None` to represent the absence of unknown calls? This would simplify the code below.

2024-02-27 16:26 UTC, lars-reimann commented on src/library_analyzer/processing/api/purity_analysis/model/_reference.py
> +    @staticmethod
Move static methods above the constructor.

2024-02-27 16:26 UTC, lars-reimann commented on src/library_analyzer/processing/api/purity_analysis/_build_call_graph.py
> +                    for fun in functions["__init__"]:
Use `functions.get("__init__", [])` instead. Gets rid of one level of nesting.

2024-02-27 16:26 UTC, lars-reimann commented on src/library_analyzer/processing/api/purity_analysis/_get_module_data.py
> +                self.functions[node_name] = [self.current_function_def[-1]]
```suggestion
            self.functions.setdefault(node_name, []).append(self.current_function_def[-1])
```

Or use a [`defaultdict`](https://stackoverflow.com/a/4143719).

2024-02-27 16:26 UTC, lars-reimann commented on src/library_analyzer/processing/api/purity_analysis/_get_module_data.py
> +                self.functions[node_name] = [self.current_function_def[-1]]
The same pattern is applicable elsewhere.

2024-02-27 16:26 UTC, lars-reimann commented on src/library_analyzer/processing/api/purity_analysis/_get_module_data.py
> +    #                     child.symbol.__class__ = LocalVariable
Please remove for this PR.

2024-02-27 21:53 UTC, lukarade commented on src/library_analyzer/processing/api/purity_analysis/model/_module_data.py
> +        """Get the top level receiver.
Since we added the _node_ attribute to `MemberAccess` this is no longer needed. It will be removed.

2024-02-27 22:12 UTC, lukarade commented on src/library_analyzer/processing/api/purity_analysis/model/_module_data.py
> +        The list of super classes of the class if it exists else None.
This was changed to match the possible return types of the function that calculates the supper_classes. Both types were changed to `list[ClassScope]`.

2024-02-28 07:18 UTC, lukarade commented on src/library_analyzer/processing/api/purity_analysis/model/_module_data.py
> +        self.call_references.pop(name, None)
You are right, that would be a problem. Trying to solve this, besides facing issues to do so, I have found an even bigger problem which scale I'm not quite sure of. I will show it to you tomorrow.

2024-02-29 16:23 UTC, lars-reimann approved these changes
Nice work!

2024-02-29 16:24 UTC, merged